### PR TITLE
Update README.md - (WIP: Review, edit text, and include attack sketch for uptane/uptane#26)

### PR DESCRIPTION
**Pull request by vladimir-v-diaz**
Edits to text after following the instructions and running the demo.  

Should we make it clear how users can start the Python interpreter and enter commands on the Python (>>>) prompt?  Not everyone trying out the reference implementation might be familiar with Python.

### CODE REVIEW

**Comment by vladimir-v-diaz** [comment]
GitHub encourages users to keep the commit message short (and add more detail in the commit summary).  Let me know if you prefer longer, more detailed commit messages.

**Comment by awwad** [comment]
I'm fine either way on commit messages. I do prefer pull request titles to be more expressive, since they're viewed in a list of PRs and should be distinguishable, I guess, but for commit messages, short message && details in summary makes sense.

**Comment by vladimir-v-diaz** [comment]
Updated the PR title.  Be default, the GitHub online editor adds "Update README.md" and puts the cursor on the summary input box.  I usually just put the cursor over the PR title to see the commit summary, but it's probably more convenient if the titles were distinguishable.

**Comment by vladimir-v-diaz** [comment]
I can add the rest of Python interpreter prompts, if you prefer.  From past experience, it wasn't clear to users which commands should be entered on the interpreter prompt, bash shell, or written to a Python module.

**Pull request merged**
